name: Build

on: 
  push:
  workflow_dispatch:
  
jobs:
  debug_app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: temurin 
        cache: gradle
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew :app:assembleDebug